version: "3"
services:
  reverseproxy:
      image: reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: udagram-api-user
    environment:
      POSTGRES_USERNAME: hamed
      POSTGRES_PASSWORD: pass_2022 
      POSTGRES_DB: postgres 
      POSTGRES_HOST: cd0354-db.cezb9fgof0pi.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1 
      AWS_PROFILE: default 
      AWS_BUCKET: cd0354-bucket
      JWT_SECRET: testing
      URL: "http://a694a06487ecf4e8a9bcf7dfc5b2b818-1741037734.us-east-1.elb.amazonaws.com:8080/api/v0"
  backend-feed:
    image: udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: hamed
      POSTGRES_PASSWORD: pass_2022 
      POSTGRES_DB: postgres
      POSTGRES_HOST: cd0354-db.cezb9fgof0pi.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1
      AWS_PROFILE: default 
      AWS_BUCKET: cd0354-bucket
      JWT_SECRET: testing
      URL: "http://a694a06487ecf4e8a9bcf7dfc5b2b818-1741037734.us-east-1.elb.amazonaws.com:8080/api/v0"
  frontend:
    image: udagram-frontend:local
    ports:
      - "8100:80"

